version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres